pipeline tweaks

diff --git a/azure-pipelines-example.yml b/azure-pipelines-example.yml
--- a/azure-pipelines-example.yml
+++ b/azure-pipelines-example.yml
@@ -79,28 +79,28 @@ stages:
           AGENT_IP=$(curl -s https://api.ipify.org)
           echo "##vso[task.setvariable variable=AGENT_IP;isOutput=true]$AGENT_IP"
 
-    # Whitelist Azure DevOps agent IP in PostgreSQL Flexible Server
-    - task: AzureCLI@2
-      displayName: 'Create firewall rule'
-      name: CreateFirewallRule
-      inputs:
-        azureSubscription: '$(azureResourceServiceConnection)'
-        scriptType: 'bash'
-        scriptLocation: 'inlineScript'
-        inlineScript: |
-          az postgres flexible-server firewall-rule create \
-            --resource-group $(resourceGroupName) \
-            --name $(postgresServerName) \
-            --rule-name "AzureDevOps-$(Build.BuildId)" \
-            --start-ip-address $(GetAgentIP.AGENT_IP) \
-            --end-ip-address $(GetAgentIP.AGENT_IP)
+    # # Whitelist Azure DevOps agent IP in PostgreSQL Flexible Server
+    # - task: AzureCLI@2
+    #   displayName: 'Create firewall rule'
+    #   name: CreateFirewallRule
+    #   inputs:
+    #     azureSubscription: '$(azureResourceServiceConnection)'
+    #     scriptType: 'bash'
+    #     scriptLocation: 'inlineScript'
+    #     inlineScript: |
+    #       az postgres flexible-server firewall-rule create \
+    #         --resource-group $(resourceGroupName) \
+    #         --name $(postgresServerName) \
+    #         --rule-name "AzureDevOps-$(Build.BuildId)" \
+    #         --start-ip-address $(GetAgentIP.AGENT_IP) \
+    #         --end-ip-address $(GetAgentIP.AGENT_IP)
           
-          # Store the exit code to verify rule was created
-          RULE_CREATE_EXIT=$?
-          if [ $RULE_CREATE_EXIT -ne 0 ]; then
-            echo "Failed to create firewall rule"
-            exit $RULE_CREATE_EXIT
-          fi
+    #       # Store the exit code to verify rule was created
+    #       RULE_CREATE_EXIT=$?
+    #       if [ $RULE_CREATE_EXIT -ne 0 ]; then
+    #         echo "Failed to create firewall rule"
+    #         exit $RULE_CREATE_EXIT
+    #       fi
 
     # Run database migrations
     # - task: DotNetCoreCLI@2
@@ -110,20 +110,20 @@ stages:
     #     projects: 'Migrations/Migrations.csproj'
     #     arguments: '--configuration Release'
 
-    # Always clean up firewall rule
-    - task: AzureCLI@2
-      displayName: 'Remove firewall rule'
-      condition: always()
-      inputs:
-        azureSubscription: '$(azureResourceServiceConnection)'
-        scriptType: 'bash'
-        scriptLocation: 'inlineScript'
-        inlineScript: |
-          az postgres flexible-server firewall-rule delete \
-            --resource-group $(resourceGroupName) \
-            --name $(postgresServerName) \
-            --rule-name "AzureDevOps-$(Build.BuildId)" \
-            --yes
+    # # Always clean up firewall rule
+    # - task: AzureCLI@2
+    #   displayName: 'Remove firewall rule'
+    #   condition: always()
+    #   inputs:
+    #     azureSubscription: '$(azureResourceServiceConnection)'
+    #     scriptType: 'bash'
+    #     scriptLocation: 'inlineScript'
+    #     inlineScript: |
+    #       az postgres flexible-server firewall-rule delete \
+    #         --resource-group $(resourceGroupName) \
+    #         --name $(postgresServerName) \
+    #         --rule-name "AzureDevOps-$(Build.BuildId)" \
+    #         --yes
 
     # Push the built image to the registry
     - task: Docker@2
